apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: docker-registry-eu.mdevlab.com/mcp-mir/postgres:master
        name: guestbook-ui
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: private-docker-reg
